name: WindyCraft
version: ${project.version}
main: net.teamfruit.windycraft.WindyCraft
api-version: 1.15
authors: [Kamesuta]

commands:
  wind:
    permission: windycraft
    usage: /wind <start|stop|vel>

permissions:
  windycraft:
    default: op
